laravel/app/routes.php
<?php

// Front-end

Route::get('/', ['as' => 'home', 'uses' => 'HomeController@index']);
Route::get('empresa', ['as' => 'empresa', 'uses' => 'EmpresaController@index']);
Route::get('atuacao', ['as' => 'atuacao', 'uses' => 'AtuacaoController@index']);
Route::get('projetos', ['as' => 'projetos', 'uses' => 'ProjetosController@index']);
Route::get('clientes', ['as' => 'clientes', 'uses' => 'ClientesController@index']);
Route::get('parceiros', ['as' => 'parceiros', 'uses' => 'ParceirosController@index']);
Route::get('contato', ['as' => 'contato', 'uses' => 'ContatoController@index']);
Route::post('contato', ['as' => 'contato.envio', 'uses' => 'ContatoController@envio']);


// Painel

Route::get('painel', [
    'before' => 'auth',
    'as'     => 'painel.home',
    'uses'   => 'Painel\HomeController@index'
]);

Route::get('painel/login', [
    'as'   => 'painel.login',
    'uses' => 'Painel\HomeController@login'
]);
Route::post('painel/login', [
    'as'   => 'painel.auth',
    'uses' => 'Painel\HomeController@attempt'
]);
Route::get('painel/logout', [
    'as'   => 'painel.logout',
    'uses' => 'Painel\HomeController@logout'
]);

Route::group(['prefix' => 'painel', 'before' => 'auth'], function() {
    Route::resource('banners', 'Painel\BannersController');
    Route::resource('empresa', 'Painel\EmpresaController');
    Route::resource('atuacao', 'Painel\AtuacaoController');
    Route::resource('projetos', 'Painel\ProjetosController');
    Route::resource('clientes', 'Painel\ClientesController');
    Route::resource('parceiros', 'Painel\ParceirosController');
    Route::resource('contato/recebidos', 'Painel\ContatosRecebidosController');
    Route::resource('contato', 'Painel\ContatoController');
    Route::resource('usuarios', 'Painel\UsuariosController');

    Route::post('ajax/order', 'Painel\AjaxController@order');
    Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
});

laravel/app/models/Parceiro.php
<?php

class Parceiro extends Eloquent
{

    protected $table = 'parceiros';

    protected $hidden = [];

    protected $guarded = ['id'];

    public function scopeOrdenados($query)
    {
        return $query->orderBy('ordem', 'ASC')->orderBy('id', 'DESC');
    }

}

laravel/app/controllers/ParceirosController.php
<?php

class ParceirosController extends BaseController {

	public function index()
	{
        View::share('titulo', 'Parceiros');

        $parceiros = Parceiro::ordenados()->get();

		return $this->view('frontend.parceiros', compact('parceiros'));
	}

}

laravel/app/controllers/painel/AjaxController.php
<?php

namespace Painel;

use \Request, \Input, \DB, \Controller;

class AjaxController extends Controller {

    function order()
    {

        if (!Request::ajax()) return false;

        $menu   = Input::get('data');
        $tabela = Input::get('tabela');

        for ($i = 0; $i < count($menu); $i++) {
            DB::table($tabela)->where('id', $menu[$i])->update(array('ordem' => $i));
        }

        return json_encode($menu);

    }

}

laravel/app/controllers/painel/AtuacaoController.php
<?php

namespace Painel;

use \Atuacao, \View, \Input, \Session, \Redirect, \Validator, \CropImage;

class AtuacaoController extends BasePainelController {

    private $validation_rules = [
        'texto'  => 'required'
    ];

    public function index()
    {
        $paginas = Atuacao::get();

        return $this->view('painel.atuacao.index', compact('paginas'));
    }

    public function edit($id)
    {
        $pagina = Atuacao::findOrFail($id);

        return $this->view('painel.atuacao.edit', compact('pagina'));
    }

    public function update($id)
    {
        $pagina = Atuacao::findOrFail($id);
        $input  = Input::all();

        $validate = Validator::make($input, $this->validation_rules);

        if ($validate->fails()) {
            return Redirect::back()
                ->withErrors($validate)
                ->withInput();
        }

        try {

            $pagina->update($input);
            Session::flash('sucesso', 'Página alterada com sucesso.');

            return Redirect::route('painel.atuacao.index');

        } catch (\Exception $e) {

            return Redirect::back()
                ->withErrors(['Erro ao alterar página.'])
                ->withInput();

        }
    }

}

laravel/app/controllers/painel/BannersController.php
<?php

namespace Painel;

use \Banner, \View, \Input, \Session, \Redirect, \Validator, \CropImage;

class BannersController extends BasePainelController {

    private $validation_rules = [
        'imagem' => 'required|image',
        'texto'  => 'required',
    ];

    private $image_config = [
        'width'  => 2000,
        'height' => null,
        'upsize' => true,
        'path'   => 'assets/img/banners/'
    ];

    public function index()
    {
        $banners = Banner::ordenados()->get();

        return $this->view('painel.banners.index', compact('banners'));
    }

    public function create()
    {
        return $this->view('painel.banners.create');
    }

    public function store()
    {
        $input = Input::all();

        $validate = Validator::make($input, $this->validation_rules);

        if ($validate->fails()) {
            return Redirect::back()
                ->withErrors($validate)
                ->withInput();
        }

        try {

            $input['imagem'] = CropImage::make('imagem', $this->image_config);
            Banner::create($input);
            Session::flash('sucesso', 'Banner adicionado com sucesso.');

            return Redirect::route('painel.banners.index');

        } catch (\Exception $e) {

            return Redirect::back()
                ->withErrors(['Erro ao adicionar banner.'])
                ->withInput();

        }
    }

    public function edit($id)
    {
        $banner = Banner::findOrFail($id);

        return $this->view('painel.banners.edit', compact('banner'));
    }

    public function update($id)
    {
        $banner = Banner::findOrFail($id);
        $input  = Input::all();

        $this->validation_rules['imagem'] = 'image';
        $validate = Validator::make($input, $this->validation_rules);

        if ($validate->fails()) {
            return Redirect::back()
                ->withErrors($validate)
                ->withInput();
        }

        try {

            if (Input::hasFile('imagem')) {
                $input['imagem'] = CropImage::make('imagem', $this->image_config);
            } else {
                unset($input['imagem']);
            }

            $banner->update($input);
            Session::flash('sucesso', 'Banner alterado com sucesso.');

            return Redirect::route('painel.banners.index');

        } catch (\Exception $e) {

            return Redirect::back()
                ->withErrors(['Erro ao alterar banner.'])
                ->withInput();

        }
    }

    public function destroy($id)
    {
        try {

            banner::destroy($id);
            Session::flash('sucesso', 'Banner removido com sucesso.');

            return Redirect::route('painel.banners.index');

        } catch (\Exception $e) {

            return Redirect::back()->withErrors(['Erro ao remover banner.']);

        }
    }

}

laravel/app/controllers/painel/BasePainelController.php
<?php

namespace Painel;

use \View, \ContatoRecebido;

class BasePainelController extends \Controller {

    protected $layout = 'painel.common.template';

    protected function setupLayout()
    {
        if ( ! is_null($this->layout))
        {
            $recebidos_count = ContatoRecebido::naoLidos()->count();
            View::share(compact('recebidos_count'));
            $this->layout = View::make($this->layout);
        }
    }

    protected function view($path, array $data = [])
    {
        $this->layout->content = View::make($path, $data);
    }

}

laravel/app/controllers/painel/ClientesController.php
<?php

namespace Painel;

use \Cliente, \View, \Input, \Session, \Redirect, \Validator, \CropImage;

class ClientesController extends BasePainelController {

    private $validation_rules = [
        'marca'  => 'required|image',
        'titulo' => 'required',
        'texto'  => 'required'
    ];

    private $image_config = [
        'width'  => 210,
        'height' => 210,
        'path'   => 'assets/img/clientes/'
    ];

    public function index()
    {
        $clientes = Cliente::ordenados()->get();

        return $this->view('painel.clientes.index', compact('clientes'));
    }

    public function create()
    {
        return $this->view('painel.clientes.create');
    }

    public function store()
    {
        $input = Input::all();

        $validate = Validator::make($input, $this->validation_rules);

        if ($validate->fails()) {
            return Redirect::back()
                ->withErrors($validate)
                ->withInput();
        }

        try {

            $input['marca'] = CropImage::make('marca', $this->image_config);
            Cliente::create($input);
            Session::flash('sucesso', 'Cliente adicionado com sucesso.');

            return Redirect::route('painel.clientes.index');

        } catch (\Exception $e) {

            return Redirect::back()
                ->withErrors(['Erro ao adicionar cliente.'])
                ->withInput();

        }
    }

    public function edit($id)
    {
        $cliente = Cliente::findOrFail($id);

        return $this->view('painel.clientes.edit', compact('cliente'));
    }

    public function update($id)
    {
        $cliente = Cliente::findOrFail($id);
        $input   = Input::all();

        $this->validation_rules['marca'] = 'image';
        $validate = Validator::make($input, $this->validation_rules);

        if ($validate->fails()) {
            return Redirect::back()
                ->withErrors($validate)
                ->withInput();
        }

        try {

            if (Input::hasFile('marca')) {
                $input['marca'] = CropImage::make('marca', $this->image_config);
            } else {
                unset($input['marca']);
            }

            $cliente->update($input);
            Session::flash('sucesso', 'Cliente alterado com sucesso.');

            return Redirect::route('painel.clientes.index');

        } catch (\Exception $e) {

            return Redirect::back()
                ->withErrors(['Erro ao alterar cliente.'])
                ->withInput();

        }
    }

    public function destroy($id)
    {
        try {

            cliente::destroy($id);
            Session::flash('sucesso', 'Cliente removido com sucesso.');

            return Redirect::route('painel.clientes.index');

        } catch (\Exception $e) {

            return Redirect::back()->withErrors(['Erro ao remover cliente.']);

        }
    }

}

laravel/app/controllers/painel/ContatoController.php
<?php

namespace Painel;

use \Contato, \Input, \Session, \Redirect, \Validator;

class ContatoController extends BasePainelController {

    private $validation_rules = [
        'email'      => 'required|email',
        'telefone'   => 'required',
        'endereco'   => 'required',
        'googlemaps' => 'required'
    ];

    public function index()
    {
    	$contato = Contato::first();

        return $this->view('painel.contato.index', compact('contato'));
    }

    public function update($id)
    {
        $contato = Contato::findOrFail($id);
        $input   = Input::all();

        $validate = Validator::make($input, $this->validation_rules);

        if ($validate->fails()) {
            return Redirect::back()
                ->withErrors($validate)
                ->withInput();
        }

        try {

            $contato->update($input);
            Session::flash('sucesso', 'Informações de contato alteradas com sucesso.');

            return Redirect::route('painel.contato.index');

        } catch (\Exception $e) {

            return Redirect::back()
                ->withErrors(['Erro ao alterar informações de contato.'])
                ->withInput();

        }
    }

}

laravel/app/controllers/painel/ContatosRecebidosController.php
<?php

namespace Painel;

use \ContatoRecebido, \Session, \Redirect;

class ContatosRecebidosController extends BasePainelController {

    public function index()
    {
        $contatos_recebidos = ContatoRecebido::orderBy('id', 'DESC')->paginate(10);

        return $this->view('painel.contatosrecebidos.index', compact('contatos_recebidos'));
    }

    public function show($id)
    {
        $contato = ContatoRecebido::findOrFail($id);
        $contato->update(['lido' => 1]);

        $recebidos_count = ContatoRecebido::naoLidos()->count();
        \View::share(compact('recebidos_count'));

        return $this->view('painel.contatosrecebidos.show', compact('contato'));
    }

    public function destroy($id)
    {
        try {

            ContatoRecebido::destroy($id);
            Session::flash('sucesso', 'Mensagem removida com sucesso.');

            return Redirect::route('painel.contato.recebidos.index');

        } catch (\Exception $e) {

            return Redirect::back()->withErrors(['Erro ao remover mensagem.']);

        }
    }

}

laravel/app/controllers/painel/EmpresaController.php
<?php

namespace Painel;

use \Empresa, \Input, \Session, \Redirect, \Validator;

class EmpresaController extends BasePainelController {

    private $validation_rules = [
        'titulo'   => 'required',
        'texto'    => 'required',
        'chamada1' => 'required',
        'chamada2' => 'required',
        'chamada3' => 'required'
    ];

    public function index()
    {
    	$empresa = Empresa::first();

        return $this->view('painel.empresa.index', compact('empresa'));
    }

    public function update($id)
    {
        $empresa = Empresa::findOrFail($id);
        $input   = Input::all();

        $validate = Validator::make($input, $this->validation_rules);

        if ($validate->fails()) {
            return Redirect::back()
                ->withErrors($validate)
                ->withInput();
        }

        try {

            $empresa->update($input);
            Session::flash('sucesso', 'Página alterada com sucesso.');

            return Redirect::route('painel.empresa.index');

        } catch (\Exception $e) {

            return Redirect::back()
                ->withErrors(['Erro ao alterar página.'])
                ->withInput();

        }
    }

}

laravel/app/controllers/painel/HomeController.php
<?php

namespace Painel;

use \View, \Input, \Auth, \Session, \Redirect;

class HomeController extends BasePainelController {

    public function index()
    {
        return $this->view('painel.home');
    }

    public function login()
    {
        return $this->view('painel.login');
    }

    public function attempt()
    {
        $authvars = array(
            'username' => Input::get('username'),
            'password' => Input::get('password')
        );

        $lembrar = (Input::get('lembrar') == 'true') ? true : false;

        if (Auth::attempt($authvars, $lembrar)) {
            return Redirect::route('painel.home');
        } else {
            Session::flash('login_errors', true);
            return Redirect::route('painel.login')->withInput(Input::except('password'));
        }
    }

    public function logout()
    {
        Auth::logout();
        return Redirect::route('home');
    }

}

laravel/app/controllers/painel/ProjetosController.php
<?php

namespace Painel;

use \Projeto, \View, \Input, \Session, \Redirect, \Validator, \CropImage;

class ProjetosController extends BasePainelController {

    private $validation_rules = [
        'texto'  => 'required'
    ];

    public function index()
    {
        $paginas = Projeto::get();

        return $this->view('painel.projetos.index', compact('paginas'));
    }

    public function edit($id)
    {
        $pagina = Projeto::findOrFail($id);

        return $this->view('painel.projetos.edit', compact('pagina'));
    }

    public function update($id)
    {
        $pagina = Projeto::findOrFail($id);
        $input  = Input::all();

        $validate = Validator::make($input, $this->validation_rules);

        if ($validate->fails()) {
            return Redirect::back()
                ->withErrors($validate)
                ->withInput();
        }

        try {

            $pagina->update($input);
            Session::flash('sucesso', 'Página alterada com sucesso.');

            return Redirect::route('painel.projetos.index');

        } catch (\Exception $e) {

            return Redirect::back()
                ->withErrors(['Erro ao alterar página.'])
                ->withInput();

        }
    }

}

laravel/app/views/painel/parceiros/_form.blade.php
@if($errors->any())
    @foreach($errors->all() as $error)
    <div class="alert alert-block alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ $error }}
    </div>
    @endforeach
@endif

@if(Session::has('sucesso'))
   <div class="alert alert-block alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ Session::get('sucesso') }}
    </div>
@endif

<div class="well form-group">
    {{ Form::label('marca', 'Marca') }}
@if($submitText == 'Alterar')
    <img src="{{ url('assets/img/parceiros/'.$parceiro->marca) }}" style="display:block; margin-bottom: 10px; max-width:210px;height:auto;background-color:#937493;">
@endif
    {{ Form::file('marca', ['class' => 'form-control']) }}
</div>

<div class="form-group">
    {{ Form::label('titulo', 'Título') }}
    {{ Form::text('titulo', null, ['class' => 'form-control']) }}
</div>

<div class="form-group">
    {{ Form::label('texto', 'Texto') }}
    {{ Form::textarea('texto', null, ['class' => 'form-control ckeditor', 'data-editor' => 'padrao']) }}
</div>

{{ Form::submit($submitText, ['class' => 'btn btn-success']) }}

<a href="{{ route('painel.parceiros.index') }}" class="btn btn-default btn-voltar">Voltar</a>

laravel/app/views/painel/parceiros/create.blade.php
@section('content')

    <legend>
        <h2>Adicionar Parceiro</h2>
    </legend>

    {{ Form::open(['route' => 'painel.parceiros.store', 'files' => true]) }}

        @include('painel.parceiros._form', ['submitText' => 'Inserir'])

    {{ Form::close() }}

@stop

laravel/app/views/painel/parceiros/edit.blade.php
@section('content')

    <legend>
        <h2>Editar Parceiro</h2>
    </legend>

    {{ Form::model($parceiro, [
        'route' => ['painel.parceiros.update', $parceiro->id],
        'method' => 'patch', 'files' => true])
    }}

        @include('painel.parceiros._form', ['submitText' => 'Alterar'])

    {{ Form::close() }}

@stop

laravel/app/views/painel/parceiros/index.blade.php
@section('content')

    @if($errors->any())
        @foreach($errors->all() as $error)
        <div class="alert alert-block alert-danger">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ $error }}
        </div>
        @endforeach
    @endif

    @if(Session::has('sucesso'))
       <div class="alert alert-block alert-success">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ Session::get('sucesso') }}
        </div>
    @endif

    <legend>
        <h2>
            Parceiros
            <a href="{{ route('painel.parceiros.create') }}" class="btn btn-success btn-sm pull-right"><span class="glyphicon glyphicon-plus" style="margin-right:10px;"></span>Adicionar Parceiro</a>
        </h2>
    </legend>

    @if(count($parceiros))
    <table class="table table-striped table-bordered table-hover table-sortable" data-tabela="parceiros">
        <thead>
            <tr>
                <th>Ordenar</th>
                <th>Marca</th>
                <th>Título</th>
                <th><span class="glyphicon glyphicon-cog"></span></th>
            </tr>
        </thead>

        <tbody>
        @foreach ($parceiros as $parceiro)

            <tr class="tr-row" id="id_{{ $parceiro->id }}">
                <td>
                    <a href="#" class="btn btn-info btn-sm btn-move">
                        <span class="glyphicon glyphicon-move"></span>
                    </a>
                </td>
                <td><img src="{{ url('assets/img/parceiros/'.$parceiro->marca) }}" alt="" style="width:100%;max-width:100px;height:auto;background-color:#937493;"></td>
                <td>{{ $parceiro->titulo }}</td>
                <td class="crud-actions">
                    {{ Form::open(array('route' => array('painel.parceiros.destroy', $parceiro->id), 'method' => 'delete')) }}

                    <div class="btn-group btn-group-sm">
                        <a href="{{ route('painel.parceiros.edit', $parceiro->id ) }}" class="btn btn-primary btn-sm pull-left">
                            <span class="glyphicon glyphicon-pencil" style="margin-right:10px;"></span>Editar
                        </a>

                        <button type="submit" class="btn btn-danger btn-sm btn-delete"><span class="glyphicon glyphicon-remove" style="margin-right:10px;"></span>Excluir</button>
                    </div>

                    {{ Form::close() }}
                </td>
            </tr>

        @endforeach
        </tbody>
    </table>
    @else
        <div class="alert alert-warning" role="alert">Nenhum parceiro cadastrado.</div>
    @endif

@stop